### ISSUE TITLE
Slideshow does not advance at the beginning even after interval time has elapsed

### ISSUE THREAD

**Issue by BackwardJet** [tejvuligonda/Web-Slideshow#7] opened 2017-03-22 06:33 UTC
It could just be loading the JS and CSS files?

**Comment by tejvuligonda** [comment] 2017-03-22 08:22
See: https://www.w3schools.com/bootstrap/bootstrap_ref_js_carousel.asp under "Carousel Options" with the option "hover". I believe this could be a user error caused by inadvertent hovering.

**Comment by tejvuligonda** [comment] 2017-03-22 08:34
After setting pause to false, the bug does not happen anymore. Thus, I am closing the issue.

**Closed as completed by tejvuligonda** 2017-03-22 08:34 UTC
Labels: bug, research
